// <auto-generated />
using System;
using EasyShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyShop.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20230705193503_IntialModel")]
    partial class IntialModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("EasyShop.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Available")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PricePerUnit")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuantityPerUnit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Supplier")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UnitsInStock")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeef3728-4733-4825-b21a-b80a0773b278"),
                            Available = true,
                            Category = "Electronics",
                            Name = "iPhone 12",
                            PricePerUnit = 999.99m,
                            QuantityPerUnit = "1 unit",
                            Supplier = "Apple",
                            UnitsInStock = 100m
                        },
                        new
                        {
                            Id = new Guid("9494116b-2b85-4d13-9e3e-6c1c08112bcc"),
                            Available = true,
                            Category = "Electronics",
                            Name = "Samsung Galaxy S21",
                            PricePerUnit = 899.99m,
                            QuantityPerUnit = "1 unit",
                            Supplier = "Samsung",
                            UnitsInStock = 50m
                        },
                        new
                        {
                            Id = new Guid("cbf9e4ca-8240-4d36-b4cd-6305ec0d81aa"),
                            Available = true,
                            Category = "Shoes",
                            Name = "Nike Air Max 270",
                            PricePerUnit = 129.99m,
                            QuantityPerUnit = "1 pair",
                            Supplier = "Nike",
                            UnitsInStock = 200m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
