// <auto-generated />
using System;
using EasyShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyShop.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20230717141301_IntialModel")]
    partial class IntialModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("EasyShop.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Available")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PricePerUnit")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuantityPerUnit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Supplier")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UnitsInStock")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("baf743c6-65ad-4f9b-a756-94dc234900d5"),
                            Available = true,
                            Category = "Electronics",
                            Name = "Wireless Mouse ABX",
                            PricePerUnit = 999.99m,
                            QuantityPerUnit = "1 unit",
                            Supplier = "ABX",
                            UnitsInStock = 100m
                        },
                        new
                        {
                            Id = new Guid("dfe6d01b-5af4-46c4-aa8a-3884cc4fe764"),
                            Available = true,
                            Category = "Electronics",
                            Name = "Computer Monitor FHD 1080P",
                            PricePerUnit = 899.99m,
                            QuantityPerUnit = "1 unit",
                            Supplier = "NewHD",
                            UnitsInStock = 50m
                        },
                        new
                        {
                            Id = new Guid("46bbb389-0c7d-410b-a728-b227a8153494"),
                            Available = true,
                            Category = "Shoes",
                            Name = "Athletic Running Tennis Shoes",
                            PricePerUnit = 129.99m,
                            QuantityPerUnit = "1 pair",
                            Supplier = "BestShoes",
                            UnitsInStock = 200m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
